scanse/sweep-sdk

libsweep/examples/example.c
libsweep/examples/example.cc
libsweep/examples/viewer.cc
libsweep/serial_unix.c
libsweep/sweep.c

Calling the stop function on the user-side is not really necessary as we're doing it on device destruction anyway if it wasn't done so far. It's more to get users familiar with the symmetric API.
I confirmed #23 being an issue with the recent units and this changeset fixing it for me.
@dcyoung can you confirm? Edit: confirmed working in issue.

Stops scanning and flushes serial device on destruction, resolves #23

---

.travis.yml
libsweep/examples/CMakeLists.txt
libsweep/examples/README.md
libsweep/examples/net.cc
libsweep/examples/net.proto

Simple Pub-Sub example:
- Publisher polls scans from device, encodes them as Protobuf messages, sends them out.
- Subscribers connect to publisher, decode messages, print to stdout.
I wanted to see how hard it would be to pull this off and at the same time provide additional examples. Maybe it helps.
See #12, #13.
References:
- http://api.zeromq.org/2-1:zmq-cpp

Adds Protobuf + ZeroMQ Networking Example

---

libsweep/README.md
libsweep/dummy.cc
libsweep/examples/example.c
libsweep/examples/example.cc
libsweep/protocol.cc
libsweep/protocol.h
libsweep/sweep.cc
libsweep/sweep.h
libsweep/sweep.hpp
sweepjs/README.md
sweepjs/index.js
sweepjs/sweepjs.cc
sweepjs/sweepjs.h
sweeppy/README.md
sweeppy/sweeppy.py

500 Hz:
750 Hz:
Looks like the signal strength goes down quite a bit from my first experiences. No real difference between 750 Hz and 1000 Hz. Resolution goes up (even though not _that_ much (?)), looks good over all!
@dcyoung @kent-williams can you take a quick look. Especially since you know more about firmware plans. I opted for the user having to explicitly specify the Hz, and let the README document the support for 500 Hz, 750 Hz and 1000 Hz.
From your docs it looks like the device can be off by ~50-100 Hz. Which means high-precision applications probably require accurate timestamps (?) (see https://github.com/scanse/sweep-sdk/issues/19).
References:
- https://github.com/scanse/sweep-sdk/commit/449565f45fea61a7b99adc942d4f6c4ecb7005b4
- …

Implements Sample Rate, resolves #21

---

libsweep/protocol.h
libsweep/sweep.cc

For #20.
@kent-williams @dcyoung can it happen that the sync bit _and_ the error bit is set? (or really: multiple bits, not specific to those two) Also any insights to error codes for other bits? Or are they unused on the firmware level, too, at the moment?

Implements Communication Error Bit, resolves #20

---

libsweep/CMakeLists.txt
libsweep/include/sweep/sweep.hpp
libsweep/man/build.sh
libsweep/man/sweep-ctl.1
libsweep/man/sweep-ctl.md
libsweep/src/sweep-ctl.cc

Adds a `sweep-ctl` binary as described in #49.
Not sure about the man page install dir on macOS and Windows. At the moment I'm using CMake's `GNUInstallDirs` module. Would be great if we can check this first before merging.

Adds sweep-ctl, resolves #49

---

sweeppy/sweeppy/__init__.py

Rationale: `ctypes.c_char_p` map C `char*` to Python byte objects.
Thus, encoding Python strings is required before passing it as argument.
This fixes a `opening serial port failed` problem when using Python 3.

sweeppy: fix Python 3 compatibility

---

.travis.yml
appveyor.yml
sweeppy/README.md
sweeppy/sweeppy/__main__.py

This allows to run the example without prior installation.

sweeppy: move test example to __main__

---

libsweep/src/unix/serial.cc

Serial device was not being properly closed on unix systems. This is ok on windows.

Added close serial port to device_destruct in unix serial.cc

---

libsweep/CMakeLists.txt
libsweep/README.md
libsweep/doc/serial_protocol_spec.md
libsweep/examples/example.c
libsweep/examples/example.cc
libsweep/examples/net.cc
libsweep/examples/viewer.cc
libsweep/include/protocol.h
libsweep/include/sweep/sweep.h
libsweep/include/sweep/sweep.hpp
libsweep/src/dummy.cc
libsweep/src/protocol.cc
libsweep/src/sweep.cc
sweepjs/README.md
sweepjs/index.js
sweepjs/sweepjs.cc
sweepjs/sweepjs.h
sweeppy/README.md
sweeppy/sweeppy/__init__.py
sweeppy/sweeppy/__main__.py

This PR brings a few changes:
1. Updated protocol to match the new firmware that is installed on devices shipping out today.
2. Updated to perform checks for status byte codes indicating failures that do not result in errors. 
3. Provide methods (and update existing methods) to wait until the device is ready before attempting to change motor speed or start scanning.
4. Add scan worker to accumulate scans in a queue using a background thread.
5. Return complete scans between 0-360 degrees (other than first scan which is inherently partial).
6. Offer alternative non-blocking functions where possible (currently only available in C library).
7. Increase delay between stop commands in the stop_scanning function to account for the device logging session data after responding to the first stop. …

Updated Protocol + Scan worker

---

libsweep/include/queue.h
libsweep/src/sweep.cc

- puts queue impl. into `queue.h`
- makes it generic on its value type
- marks thread safe members `mutable`
- no need for a `unique_ptr<queue>`, just store by value

Refactors Queue

---

libsweep/src/sweep.cc

Gets rid of the following compiler warning:
`warning C4101: 'e' : unreferenced local variable`
Change involves performing a void cast on any exception caught in the worker thread's `accumulate_scans()` method. 
No limitations over the existing code, as currently the exception isn't being used. This will likely be a temporary fix, until a later PR actually propagates the error by notifying the main thread.

Suppress compiler warning when ignoring exception

---

libsweep/doc/serial_protocol_spec.md
libsweep/include/protocol.hpp
libsweep/src/sweep.cc

Simplifies the conversion of the azimuth field. See #89 
Removes the overly complicated conversion method (`u16_to_f32`) from the protocol header, and updates the protocol docs.
Perhaps the docs should also include example conversions in languages other than js... as that really isn't the most likely use case. It was chosen as the example language more for simplicity and readability (almost like pseudo code).  But most users will likely be using c++ or something similar.

Simplify azimuth conversion

---

libsweep/README.md
libsweep/include/sweep/sweep.h
libsweep/src/dummy.cc
libsweep/src/sweep.cc

Features not exposed via `SWEEP_API` must not be exposed in the interface header.
This changeset moves some code around to cleanup the API surface.

Hides impl. details from API surface

---

CHANGELOG.md
RELEASE.md

Documenting the release process.
I also like to keep a copy of the changelog in the repo. and not only [on Github](https://github.com/scanse/sweep-sdk/releases).

Adds release documentation

---

libsweep/include/queue.hpp
libsweep/include/serial.hpp
libsweep/src/dummy.cc
libsweep/src/sweep.cc
libsweep/src/unix/serial.cc
libsweep/src/win/serial.cc

Propagates exceptions occuring in the worker thread to `sweep_device_get_scan`.
- Modifies queue code to play nice with move-only types
- Manages dynamically allocated memory via unqiue_ptr as long as possible to prevent any memory leaks
- Combines pointer to scan and exception pointer (one of them being nullptr) into one struct and passes them through the queue
- Removes some redundant type defs accross the code base for consistency reasons (ccan drop that commit from the PR if prefered)
- Not yet tested (seeking early feedback)
- Actual error handling (instead of just reporting) might be desired (see https://github.com/scanse/sweep-sdk/issues/91)

Error propagation

---

CHANGELOG.md
libsweep/CMakeLists.txt
libsweep/src/sweep.cc
sweepjs/package.json

This a temporary solution to the problems described in #73. See the issue for details.
It would be nice to know the root cause of the bug, but this temporary fix will allow development of the 3d-scanner to commence.

Temp Fix for Delayed Buffering of Stop Response during Device Construction on Raspberry Pi

---

libsweep/src/unix/serial.cc

When the cable becomes unplugged the device_read function goes into an infinite loop causing the caller to hang and the process to consume 100% CPU cycles. This failure mode can be more gracefully handled by detecting EOF.
* https://github.com/scanse/sweep-ros/issues/11
* https://github.com/scanse/sweep-sdk/issues/102
Modified Linux serial support to throw an exception if an EOF condition is detected.
The error handling facilities are not very graceful and if the caller does not handle the exception, it result in a crash in upstream programs which may not have previously been expected(but neither was a hang). I have not yet been able to fully recover the connection after handling the exception but now you atleast get a clear error message.

Unplug exception

---

libsweep/include/protocol.hpp
libsweep/src/protocol.cc
libsweep/src/sweep.cc

This is a collection of refactorings concerning the protocol functions and the `sweep_device_accumulate_scans` function. The reason those are in one PR is that they partially depend on each other.
The PRs has two main goals:
- Pushing more code that is concerned with protocol details into the protocol.hpp and .cpp files
- Refactor `sweep_scan` / `sweep_device_accumulate_scans`  in anticipation of adding time stamps and turning it into a dynamically sized datastructure.

Refactor some libsweep internals

---

libsweep/src/unix/serial.cc

This bug was causing sweep object creation to hang when trying to read the returned value from serial port. ==> Issue #72
Bitrate of the serial communication was badly set during the creation of the sweep object when using the libsweep library on Linux.
cfsetispeed(...) and cfsetospeed(...) both take a termios bitrate constant and not the bitrate directly. So should the get_baud(115200) call return the B115200 value defined in termios.h.
The fix seems to have a limitation when compiling on some MAC OS X computers. Termios constants like B115200 doesn't seem to be always defined. That's why the code uses a #ifdef as a workaround for MAC.
Thanks.

Fixed badly set bitrate causing sweep object creation to hang on Linux

---

libsweep/README.md
sweeppy/README.md

We've been receiving quite  a few support messages from people confused by the output data format of the sweeppy example. Specifically, the milli-degree angle value is throwing people off. 
This is a quick patch the sweeppy README  that clarifies the format and units of the returned samples. 
Additionally, this PR updates the libsweep and sweeppy READMEs to include links to 2 articles on using the sweep (theory of operation and best practices).
We should probably also clarify the format and units in the libsweep and sweeppy examples.  Printing a simple header before printing the sample of gathered scans would go a long way.

[Sweeppy Docs] Clarify sample units and format in sweeppy README. 

---

libsweep/src/unix/serial.cc

Fix another issue in Linux serial port configuration, which causes the issue #72

character size must be set AFTER clearing character size bits

---

libsweep/README.md

Sorry for keep bugging you with these minor changes. libsweep is now available in both ports tree and pkg hence updating the instruction. (Probably the final PR from me regarding the documentation?)
Installation instruction for FreeBSD.
N/A

Modify Installation Instruction for FreeBSD
